name: MS Teams Notification

on: [push, pull_request]
branches: [ teams-alerts ]

# push:
#     branches: [ teams-alerts ]
# pull_request:
#     branches: [ teams-alerts ]
#jobs:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Demo Step
        run: echo $GITHUB_RUN_NUMBER
      # this is the new step using the ms-teams-notification action
      - name: Notify dedicated teams channel
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: https://pearlthoughts.webhook.office.com/webhookb2/2ba26411-5156-4cf9-a749-4c9864d70b11@01539d20-c779-4da8-aca2-5c1d5a6fc8bb/IncomingWebhook/1962720c97c246638df3bf9222e5408c/3beb573c-1300-4798-bf75-e4ff50a487c6
          notification-summary: "Github Action Build Number ${{ github.run_number }} Completed for ${{ github.repository }}, Commit ID ${{ github.event.head_commit.message }}, commit ID ${{ github.event.head_commit.id }} and the outcome is  ${{ needs.build.result }}."
          notification-color: 17a2b8
          timezone: America/Denver








# name: Pipeline Name

# on:
# push:
#     branches: [ teams-alerts ]
# pull_request:
#     branches: [ teams-alerts ]
# jobs:

# build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Demo Step
#       run: echo $GITHUB_RUN_NUMBER

# notify:
#     runs-on: ubuntu-latest
#     permissions:
#       actions: 'read
#     if: always()
#     needs: build
#     steps:
#     - name: Send a Notification
#         id: notify
#         uses: thechetantalwar/teams-notify@v2
#         with:
#         teams_webhook_url: https://pearlthoughts.webhook.office.com/webhookb2/2ba26411-5156-4cf9-a749-4c9864d70b11@01539d20-c779-4da8-aca2-5c1d5a6fc8bb/IncomingWebhook/1962720c97c246638df3bf9222e5408c/3beb573c-1300-4798-bf75-e4ff50a487c6
#         message: "Github Action Build Number ${{ github.run_number }} Completed for ${{ github.repository }}, Commit ID ${{ github.event.head_commit.message }}, commit ID ${{ github.event.head_commit.id }} and the outcome is  ${{ needs.build.result }}."